//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrMangmentSystem_Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HrMangmentSystem_Shared.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect..
        /// </summary>
        public static string Auth_InvalidCurrentPassword {
            get {
                return ResourceManager.GetString("Auth_InvalidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful..
        /// </summary>
        public static string Auth_LoginSuccess {
            get {
                return ResourceManager.GetString("Auth_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be different from the current password..
        /// </summary>
        public static string Auth_NewPasswordMustBeDifferent {
            get {
                return ResourceManager.GetString("Auth_NewPasswordMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not contain parts of your email address..
        /// </summary>
        public static string Auth_Password_ContainsEmailPart {
            get {
                return ResourceManager.GetString("Auth_Password_ContainsEmailPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not contain spaces..
        /// </summary>
        public static string Auth_Password_HasWhitespace {
            get {
                return ResourceManager.GetString("Auth_Password_HasWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too common. Please choose a stronger one..
        /// </summary>
        public static string Auth_Password_IsCommon {
            get {
                return ResourceManager.GetString("Auth_Password_IsCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one digit..
        /// </summary>
        public static string Auth_Password_MissingDigit {
            get {
                return ResourceManager.GetString("Auth_Password_MissingDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter..
        /// </summary>
        public static string Auth_Password_MissingLower {
            get {
                return ResourceManager.GetString("Auth_Password_MissingLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character..
        /// </summary>
        public static string Auth_Password_MissingSpecial {
            get {
                return ResourceManager.GetString("Auth_Password_MissingSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter..
        /// </summary>
        public static string Auth_Password_MissingUpper {
            get {
                return ResourceManager.GetString("Auth_Password_MissingUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Auth_Password_Required {
            get {
                return ResourceManager.GetString("Auth_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long..
        /// </summary>
        public static string Auth_Password_TooShort {
            get {
                return ResourceManager.GetString("Auth_Password_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        public static string Auth_PasswordChanged {
            get {
                return ResourceManager.GetString("Auth_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized..
        /// </summary>
        public static string Auth_Unauthorized {
            get {
                return ResourceManager.GetString("Auth_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeletedByEmployeeId is required..
        /// </summary>
        public static string Delete_DeletedByRequired {
            get {
                return ResourceManager.GetString("Delete_DeletedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this resource..
        /// </summary>
        public static string Delete_Forbidden {
            get {
                return ResourceManager.GetString("Delete_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department cannot be parent of itself..
        /// </summary>
        public static string Department_CannotBeOwnParent {
            get {
                return ResourceManager.GetString("Department_CannotBeOwnParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department code is already in use..
        /// </summary>
        public static string Department_CodeExists {
            get {
                return ResourceManager.GetString("Department_CodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeptName and Code are required..
        /// </summary>
        public static string Department_CodeRequired {
            get {
                return ResourceManager.GetString("Department_CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department created successfully..
        /// </summary>
        public static string Department_Created {
            get {
                return ResourceManager.GetString("Department_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department deleted successfully..
        /// </summary>
        public static string Department_Deleted {
            get {
                return ResourceManager.GetString("Department_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete department because it has child departments..
        /// </summary>
        public static string Department_HasChildren {
            get {
                return ResourceManager.GetString("Department_HasChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete department because employees are assigned to it..
        /// </summary>
        public static string Department_HasEmployees {
            get {
                return ResourceManager.GetString("Department_HasEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments loaded successfully..
        /// </summary>
        public static string Department_ListLoaded {
            get {
                return ResourceManager.GetString("Department_ListLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete department because it has a manager assigned..
        /// </summary>
        public static string Department_ManagerAssigned {
            get {
                return ResourceManager.GetString("Department_ManagerAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department not found..
        /// </summary>
        public static string Department_NotFound {
            get {
                return ResourceManager.GetString("Department_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent department not found..
        /// </summary>
        public static string Department_ParentNotFound {
            get {
                return ResourceManager.GetString("Department_ParentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department updated successfully..
        /// </summary>
        public static string Department_Updated {
            get {
                return ResourceManager.GetString("Department_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name, last name and email are required..
        /// </summary>
        public static string Employee_BasicFieldsRequired {
            get {
                return ResourceManager.GetString("Employee_BasicFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee created successfully..
        /// </summary>
        public static string Employee_Created {
            get {
                return ResourceManager.GetString("Employee_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee deleted successfully..
        /// </summary>
        public static string Employee_Deleted {
            get {
                return ResourceManager.GetString("Employee_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department for this employee was not found..
        /// </summary>
        public static string Employee_DepartmentNotFound {
            get {
                return ResourceManager.GetString("Employee_DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee with this email already exists..
        /// </summary>
        public static string Employee_EmailExists {
            get {
                return ResourceManager.GetString("Employee_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete employee because they have subordinates..
        /// </summary>
        public static string Employee_HasSubordinates {
            get {
                return ResourceManager.GetString("Employee_HasSubordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date of birth..
        /// </summary>
        public static string Employee_InvalidDateOfBirth {
            get {
                return ResourceManager.GetString("Employee_InvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid employment start date..
        /// </summary>
        public static string Employee_InvalidEmploymentDate {
            get {
                return ResourceManager.GetString("Employee_InvalidEmploymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete employee because they are assigned as manager..
        /// </summary>
        public static string Employee_IsDepartmentManager {
            get {
                return ResourceManager.GetString("Employee_IsDepartmentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees loaded successfully..
        /// </summary>
        public static string Employee_ListLoaded {
            get {
                return ResourceManager.GetString("Employee_ListLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee must be at least 18 years old..
        /// </summary>
        public static string Employee_MustBeAdult {
            get {
                return ResourceManager.GetString("Employee_MustBeAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee not found..
        /// </summary>
        public static string Employee_NotFound {
            get {
                return ResourceManager.GetString("Employee_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is required..
        /// </summary>
        public static string Employee_PositionRequired {
            get {
                return ResourceManager.GetString("Employee_PositionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee updated successfully..
        /// </summary>
        public static string Employee_Updated {
            get {
                return ResourceManager.GetString("Employee_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee is already has role.
        /// </summary>
        public static string EmployeeRole_AlreadyAssigned {
            get {
                return ResourceManager.GetString("EmployeeRole_AlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee role defualt assigned to employee.
        /// </summary>
        public static string EmployeeRole_Assigned {
            get {
                return ResourceManager.GetString("EmployeeRole_Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee role not found..
        /// </summary>
        public static string EmployeeRole_NotFound {
            get {
                return ResourceManager.GetString("EmployeeRole_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee roles updated successfully..
        /// </summary>
        public static string EmployeeRole_Updated {
            get {
                return ResourceManager.GetString("EmployeeRole_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID mismatch..
        /// </summary>
        public static string Generic_IdMismatch {
            get {
                return ResourceManager.GetString("Generic_IdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request data..
        /// </summary>
        public static string Generic_InvalidData {
            get {
                return ResourceManager.GetString("Generic_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found..
        /// </summary>
        public static string Generic_NotFound {
            get {
                return ResourceManager.GetString("Generic_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        public static string Generic_OperationFailed {
            get {
                return ResourceManager.GetString("Generic_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully..
        /// </summary>
        public static string Generic_OperationSucceeded {
            get {
                return ResourceManager.GetString("Generic_OperationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string Generic_UnexpectedError {
            get {
                return ResourceManager.GetString("Generic_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job position is already closed..
        /// </summary>
        public static string JobPosition_AlreadyClosed {
            get {
                return ResourceManager.GetString("JobPosition_AlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job position is already open..
        /// </summary>
        public static string JobPosition_AlreadyOpen {
            get {
                return ResourceManager.GetString("JobPosition_AlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job position was closed successfully..
        /// </summary>
        public static string JobPosition_Closed {
            get {
                return ResourceManager.GetString("JobPosition_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing date cannot be in the past.
        /// </summary>
        public static string JobPosition_ClosingDateInvalid {
            get {
                return ResourceManager.GetString("JobPosition_ClosingDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job position created successfully..
        /// </summary>
        public static string JobPosition_Created {
            get {
                return ResourceManager.GetString("JobPosition_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job position deleted successfully..
        /// </summary>
        public static string JobPosition_Deleted {
            get {
                return ResourceManager.GetString("JobPosition_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department with Id {0}  was not found.
        /// </summary>
        public static string JobPosition_DepartmentNotFound {
            get {
                return ResourceManager.GetString("JobPosition_DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job position details loaded successfully..
        /// </summary>
        public static string JobPosition_DetailsLoaded {
            get {
                return ResourceManager.GetString("JobPosition_DetailsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job position with Id {0} has applications and cannot be deleted..
        /// </summary>
        public static string JobPosition_HasApplications {
            get {
                return ResourceManager.GetString("JobPosition_HasApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job positions list loaded successfully..
        /// </summary>
        public static string JobPosition_ListLoaded {
            get {
                return ResourceManager.GetString("JobPosition_ListLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job position with Id {0} was not found..
        /// </summary>
        public static string JobPosition_NotFound {
            get {
                return ResourceManager.GetString("JobPosition_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job position was reopened successfully..
        /// </summary>
        public static string JobPosition_Reopened {
            get {
                return ResourceManager.GetString("JobPosition_Reopened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements are required..
        /// </summary>
        public static string JobPosition_RequirementRequired {
            get {
                return ResourceManager.GetString("JobPosition_RequirementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to req.
        /// </summary>
        public static string JobPosition_TitleRequired {
            get {
                return ResourceManager.GetString("JobPosition_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job position updated successfully..
        /// </summary>
        public static string JobPosition_Updated {
            get {
                return ResourceManager.GetString("JobPosition_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid page number..
        /// </summary>
        public static string Pagination_InvalidPageNumber {
            get {
                return ResourceManager.GetString("Pagination_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid page size..
        /// </summary>
        public static string Pagination_InvalidPageSize {
            get {
                return ResourceManager.GetString("Pagination_InvalidPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role employee not found.
        /// </summary>
        public static string Role_NotFound {
            get {
                return ResourceManager.GetString("Role_NotFound", resourceCulture);
            }
        }
    }
}
